// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yuyycmjwzjivvaexxlzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1eXljbWp3emppdnZhZXh4bHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMjUxOTMsImV4cCI6MjA4NDkwMTE5M30.IPUvbKMjnFsdLc6z_9O0BNOzB1eyiKMr6VBWMpi__LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);